spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hzb_mysql:3306/erp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: erp
    password: 111
  redis:
    database: 0
    host: hzb_redis
    port: 6379
    password:

logging:
  level:
    root: warn

system:
  # 前端的站点网址
  domain: http://erp2.hzb-it.com
  # 前端站点的存放目录,本目录用于图片等资源上传
  staticDir: /home/html/
  # 日志存放目录
  logDir: /home/log/
