spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erp?useUnicode=true&characterEncoding=utf-8&serverTimezone=CST&useSSL=false
    username: erp
    password: 111
  redis:
    database: 0
    host: localhost
    port: 6379
    password:

logging:
  level:
    root: info

system:
  domain: http://erp2.hzb-it.com
  staticDir: /eduerpdata/static/
  logDir: /eduerpdata/logs/
