server:
  port: 8106
  servlet:
    context-path: /app

spring:
  profiles:
    active: dev
  jackson:
    time-zone: CST
  application:
    name: EduErp
  servlet:
    multipart:
      max-request-size: 20MB # 上传文件总的最大值
      max-file-size: 10MB   # 单个文件的最大值
  redis:
    jedis:
      pool:
        max-active: 200
        min-idle: 20
        max-wait: 3000
  mail:
    host: smtp.163.com
    username: erp@163.com
    password: 11
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
    protocol: smtps

logging:
  file:
    path: ${system.logDir}

#  security:
#    user:
#      name: user
#      password: ***

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  #    banner: false
  type-enums-package: com.hzb.erp.common.enums
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

system:
  version: 1.0.1125
  # 是否是演示demo（会限制关键操作） 生产环境是false！！！
  isDemo: true
  # 带http的域名
  domain:
  # 静态文件目录
  staticDir:
  # 日志文件夹
  logDir:
  # 上传文件夹
  uploadDir: ${system.staticDir}uploads/
  # 上传图片最大size 10MB
  uploadImgMaxSize: 10485760
  # 上传文件src路径前缀
  uploadFileUrlPrefix: ${system.domain}/app/static/uploads/
  # 刷新token秒数 离token过期前秒数
  jwtTokenRefreshSec: 14400
  # token过期秒数
  jwtExpiredTtlSec: 28800
  # 跨域域名设置 不设置表示不限域名
  allowOrigin:
    - ${system.domain}
    - http://localhost:8001
    - http://localhost:8002
    - http://localhost:8080
    - http://localhost:8081
    - http://localhost:8082
  # 配置放行策略 跳过security
  securityIgnoringMatchers:
    - /doc.html
    - /swagger-ui.html
    - /swagger/**
    - /v2/api-docs
    - /v2/api-docs-ext/**
    - /swagger-resources/**
    - /favicon.ico
    - /webjars/**
    - /common/open/**
    - /sCenter/open/**
    - /wx/portal/**
    - /wx/login/**
    - /wx/jsapi/**
    #    - /wx/menu/**
  # 黑名单的ip,禁止访问该系统
  blackList:

  # 微信公众号配置
  wxmp:
    useRedis: false
    defaultConfIndex: 0
    configs:
      # 公众号配置，可以设置多组
      - name: default
        appId: 11
        secret: 11
        token: 11
        aesKey: 11
