spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost.94:3306/erp?useUnicode=true&characterEncoding=utf-8&serverTimezone=CST&useSSL=false
    username: erp
    password: 111
  redis:
    database: 0
    host: 114.115.185.94
    port: 8879
    password: 111

logging:
  level:
    root: info

system:
  domain: http://erp2.hzb-it.com
  staticDir: /eduerpdata/static/
  logDir: /eduerpdata/logs/
